USER = {
    "key": "greve",
    "oid": "7a38f75b-a896-499d-89d6-579cb367314d",
    "role": "butik",
}

TICKETS = [
    {
        "title": "Betalingsterminal afviser Dankort",
        "description": "Alle Dankort afvises ved kasse 1 og 2. Visa og kontant fungerer stadig. Fejl: 'Kommunikationsfejl 51'.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "note", "actor": "support1", "text": "Kommunikationsfejl 51 er typisk en netværksfejl mod PBS. Tjekker forbindelsen nu."},
            {"event_type": "comment", "actor": "greve", "text": "Problemet opstod lige efter morgenåbning kl. 07:00."},
            {"event_type": "note", "actor": "support1", "text": "Bekræftet: TLS-forbindelsen til PBS gateway fejler. Eskalerer til netværksteamet."},
        ],
    },
    {
        "title": "Lageropgørelsessystem crasher",
        "description": "Systemet til lageropgørelse lukker ned uden varsel ved scanning af varer i fryseafdelingen.",
        "priority": "medium",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "note", "actor": "support1", "text": "Crashet er sandsynligvis relateret til en bestemt varekategori. Beder dem teste med en specifik vare."},
            {"event_type": "comment", "actor": "greve", "text": "Det sker hver gang vi scanner noget fra frysevarer kategori 'Frost-B'. Andre kategorier virker."},
            {"event_type": "note", "actor": "support1", "text": "Reproduceret fejlen. Ser ud til at være et korrupt produktID i databasen. Undersøger."},
        ],
    },
    {
        "title": "Netværk nede i hele butikken",
        "description": "Al internet og interne systemer er nede. Kasseapparater kører i offline-mode. Opstod kl. 08:15.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Router logger viser at WAN-forbindelsen droppede kl. 08:13. Kontakter ISP nu."},
            {"event_type": "comment", "actor": "greve", "text": "Vi har 3 kasser der ikke kan gennemføre kortbetalinger. Hvornår er det oppe?"},
            {"event_type": "note", "actor": "support2", "text": "ISP bekræfter fejl på linje. Estimeret rettelsetid: 2 timer."},
            {"event_type": "comment", "actor": "greve", "text": "Okay — vi kører kontant og offline-mode indtil videre."},
        ],
    },
    {
        "title": "Bonprinter udskriver ulæselige kvitteringer",
        "description": "Kvitteringer fra kasse 4 er ulæselige — teksten er skæv og halvt afskåret. Papir og rulle er tjekket.",
        "priority": "medium",
        "type": "support",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Printerhovedet er sandsynligvis forskudt. Beder dem tjekke om papiret er sat rigtigt i."},
            {"event_type": "comment", "actor": "greve", "text": "Papiret sidder korrekt. Problemet er det samme med en helt ny rulle."},
            {"event_type": "note", "actor": "support2", "text": "Kan se i loggen at printeren rapporterer en fejljustering. Sender vejledning til manuel kalibrering."},
        ],
    },
    {
        "title": "Overvågningskamera ved indgang er sort",
        "description": "Kameraet ved hoveddøren viser sort billede i overvågningssystemet. Andre kameraer virker.",
        "priority": "medium",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [],
    },
    {
        "title": "Kundedisplay viser forkert beløb",
        "description": "Kundedisplayet på kasse 3 viser andre beløb end hvad kassen registrerer. Skaber forvirring.",
        "priority": "medium",
        "type": "funktionalitet",
        "contact": "29 83 17 44",
        "events": [],
    },
    {
        "title": "Medarbejder glemt PIN til kasselogin",
        "description": "Medarbejder havde glemt sin PIN-kode.",
        "priority": "low",
        "type": "support",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "note", "actor": "support1", "text": "PIN nulstillet via admin-konsol. Ny midlertidig PIN sendt til butikschef."},
            {"event_type": "resolve", "actor": "support1"},
        ],
    },
    {
        "title": "Scanner på selvbetjening skanner samme vare flere gange",
        "description": "Scanner skannede varer 2-3 gange.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Kendt bug i firmware 3.1.4. Opdaterer til 3.1.6."},
            {"event_type": "comment", "actor": "greve", "text": "Perfekt — den fungerer normalt nu."},
            {"event_type": "resolve", "actor": "support2"},
        ],
    },
    {
        "title": "Vægt ved delikatessen ude af drift",
        "description": "Vægten viste 0 g uanset hvad der blev lagt på.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "29 83 17 44",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "comment", "actor": "greve", "text": "Vægten har stået ude ved siden af en varmelampe — ved ikke om det har noget at sige."},
            {"event_type": "note", "actor": "support2", "text": "Kalibreringsfejl — sandsynligvis udløst af varme. Kalibreret og testet med kendte vægte. OK."},
            {"event_type": "resolve", "actor": "support2"},
        ],
    },
]
