USER = {
    "key": "hvidovre",
    "oid": "3e2718de-6ead-4a85-9293-9f628722bf26",
    "role": "butik",
}

TICKETS = [
    {
        "title": "ESL-skærme opdaterer ikke priser",
        "description": "Elektroniske prisskilte i mejeriafdeling har ikke opdateret siden i går. Ca. 40 skilte berørt.",
        "priority": "medium",
        "type": "funktionalitet",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "note", "actor": "support1", "text": "ESL-gateway i Hvidovre ser ud til at have mistet forbindelsen til base-stationen. Genstarter gateway."},
            {"event_type": "comment", "actor": "hvidovre", "text": "Når tror du det er oppe igen? Vi har fået nye tilbudspriser i dag."},
            {"event_type": "note", "actor": "support1", "text": "Gateway er genstartet og begynder at synkronisere. Estimeret 30 min til fuld opdatering."},
        ],
    },
    {
        "title": "Vejemodul på selvbetjening fejler",
        "description": "Selvbetjeningskasse 1 og 3 kan ikke veje varer. Viser: 'Vægt ikke fundet'. Kasse 2 virker.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Vægtenhederne på kasse 1 og 3 er ikke registreret i systemet efter sidste opdatering. Kigger på det."},
            {"event_type": "comment", "actor": "hvidovre", "text": "Kunder klager — de kan ikke købe løsvægtsvarer."},
        ],
    },
    {
        "title": "Varebestilling kan ikke sendes",
        "description": "Elektronisk varebestilling fejler med timeout. Bestillinger gemmes ikke og vi risikerer tomme hylder.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "comment", "actor": "hvidovre", "text": "Vi har forsøgt 4 gange siden i morges. Samme fejl hver gang."},
            {"event_type": "note", "actor": "support2", "text": "Bestillingssystemets API-endpoint svarer ikke. Ser ud til at være serversiden. Eskalerer."},
        ],
    },
    {
        "title": "Håndscannere på lager reagerer ikke",
        "description": "Begge trådløse håndscannere på lageret virker ikke. Batterier er skiftet og de er paret igen.",
        "priority": "medium",
        "type": "support",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Scannerene er ikke i firmwarelisten — de er muligvis ikke opdateret. Sender firmware-link."},
            {"event_type": "comment", "actor": "hvidovre", "text": "Hvordan opdaterer vi dem? Vi har aldrig gjort det før."},
            {"event_type": "note", "actor": "support2", "text": "Sender step-by-step guide på mail til kontaktadressen."},
        ],
    },
    {
        "title": "Kontaktløs betaling virker ikke på nogen terminal",
        "description": "Alle terminaler afviser MobilePay og NFC-betaling. Fejlmelding: 'Kortlæser fejl'. Chip og PIN virker.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "44 91 28 76",
        "events": [],
    },
    {
        "title": "10 elektroniske prisskilte er sorte i vinafdelingen",
        "description": "10 ESL-skilte viser ingenting. Resten af skilte i butikken fungerer normalt.",
        "priority": "medium",
        "type": "nedbrud",
        "contact": "44 91 28 76",
        "events": [],
    },
    {
        "title": "Ny medarbejder mangler adgang til lagersystem",
        "description": "Martin Lund er oprettet men kan ikke logge ind i lagersystemet. Har brug for adgang hurtigst muligt.",
        "priority": "low",
        "type": "support",
        "contact": "44 91 28 76",
        "events": [],
    },
    {
        "title": "POS-skærm viser forkerte priser",
        "description": "Priser på skærmen stemte ikke overens med systemet efter prisopdatering.",
        "priority": "medium",
        "type": "funktionalitet",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "comment", "actor": "hvidovre", "text": "Det er specielt varer i kategori 'Mejeri' der har forkerte priser."},
            {"event_type": "note", "actor": "support1", "text": "POS-klienten havde cachet gamle priser. Cache tømt og priser er nu korrekte."},
            {"event_type": "resolve", "actor": "support1"},
        ],
    },
    {
        "title": "Dankort-terminal udskriver ikke kvittering",
        "description": "Papirrulle var tom og siddet forkert i.",
        "priority": "low",
        "type": "support",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support1", "assignee": "support1"},
            {"event_type": "note", "actor": "support1", "text": "Guidet personalet telefonisk til at isætte ny papirrulle korrekt. Virker nu."},
            {"event_type": "resolve", "actor": "support1"},
        ],
    },
    {
        "title": "Bonprinter sætter fast ved lange kvitteringer",
        "description": "Bonprinteren ved kasse 2 gik i stå. Printerdriverfejl efter opdatering.",
        "priority": "low",
        "type": "support",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Print-driver version 4.2.1 har en kendt fejl med lange jobs. Tilbagerullet til 4.1.9."},
            {"event_type": "resolve", "actor": "support2"},
        ],
    },
    {
        "title": "POS-terminal genstarter ved betaling",
        "description": "Terminal ved kasse 5 genstartet ved tryk på betalingsknap.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "44 91 28 76",
        "events": [
            {"event_type": "assign", "actor": "support2", "assignee": "support2"},
            {"event_type": "note", "actor": "support2", "text": "Strømforsyningen er defekt — viser ustabile spændinger under belastning. Udskifter."},
            {"event_type": "comment", "actor": "hvidovre", "text": "Den virker perfekt nu. Mange tak for den hurtige hjælp."},
            {"event_type": "resolve", "actor": "support2"},
        ],
    },
]
