USER = {
    "key": "karlslunde",
    "oid": "28ecb256-770c-4d8b-830f-68d936b1c96b",
    "name": "SuperBrugsen Karlslunde",
    "role": "butik",
}

TICKETS = [
    {
        "title": "Kasse 3 starter ikke op",
        "description": "Kassen tænder men går i stå under opstart. Viser fejlkode E-104. Har forsøgt genstart 3 gange.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support1", "assignee": "support1"},
            {"event_type": "note", "udfører": "support1", "text": "Fejlkode E-104 peger på korrupt boot-partition. Forsøger recovery via USB."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Tak — vi holder kassen lukket indtil videre."},
        ],
    },
    {
        "title": "Selvbetjeningskasse 2 er offline",
        "description": "SCO-kasse 2 er gået offline og kan ikke genstartes. Skærmen er sort og reagerer ikke.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support1", "assignee": "support1"},
            {"event_type": "note", "udfører": "support1", "text": "Remote-adgang virker ikke — kassen svarer ikke på netværket. Skal sandsynligvis på stedet."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Den gik offline midt i en transaktion. Kunden fik ikke gennemført sin betaling."},
        ],
    },
    {
        "title": "Ny medarbejder kan ikke logge ind på kassen",
        "description": "Camilla Frost er oprettet i systemet men kan ikke logge ind på POS. Fejl: Invalid credentials.",
        "priority": "medium",
        "type": "support",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support1", "assignee": "support1"},
            {"event_type": "note", "udfører": "support1", "text": "Kontoen er oprettet men ikke synkroniseret til POS-systemet endnu. Kører manuel synk."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Hvornår kan hun logge ind? Hun starter om 2 timer."},
        ],
    },
    {
        "title": "Kassen fryser ved kortbetaling",
        "description": "Kasse 2 hænger fast i 2-3 minutter efter hvert kortskifte. Lange køer som følge.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "33 47 21 05",
        "events": [],
    },
    {
        "title": "Kasseskuffe åbner ikke automatisk",
        "description": "Kasseskuffen på kasse 1 åbner ikke ved salg og skal åbnes manuelt med nøgle hver gang.",
        "priority": "medium",
        "type": "support",
        "contact": "33 47 21 05",
        "events": [],
    },
    {
        "title": "Etiketprinter virker ikke",
        "description": "Printerens driver var korrupt efter Windows Update.",
        "priority": "medium",
        "type": "support",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support1", "assignee": "support1"},
            {"event_type": "note", "udfører": "support1", "text": "Driver er korrupt efter KB5034441-opdatering. Deinstallerer og geninstallerer driver."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Tak — den virker nu!"},
            {"event_type": "resolve", "udfører": "support1"},
        ],
    },
    {
        "title": "WiFi-signal svagt ved køledisk",
        "description": "Access point ved køledisk var defekt.",
        "priority": "low",
        "type": "funktionalitet",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support1", "assignee": "support1"},
            {"event_type": "note", "udfører": "support1", "text": "AP-enhed ved køledisk lyser rødt og er ude af mesh-netværket. Udskifter med reserveenhed."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Super — WiFi virker nu over det hele igen."},
            {"event_type": "resolve", "udfører": "support1"},
        ],
    },
    {
        "title": "Kasse 1 genstarter spontant",
        "description": "Kassen genstartet spontant hver ~30 min. Skyldtes overheatning.",
        "priority": "high",
        "type": "nedbrud",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support2", "assignee": "support2"},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Det er sket 4 gange i dag. Kassen er varm at røre ved."},
            {"event_type": "note", "udfører": "support2", "text": "Overheatning bekræftet — intern ventilator er støvet til. Renser og tester."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Den har ikke genstartet siden I var her. Tak!"},
            {"event_type": "resolve", "udfører": "support2"},
        ],
    },
    {
        "title": "Login virker ikke efter tvunget passwordskifte",
        "description": "Karin Mose kunne ikke logge ind efter tvunget skift.",
        "priority": "medium",
        "type": "support",
        "contact": "33 47 21 05",
        "events": [
            {"event_type": "assign", "udfører": "support2", "assignee": "support2"},
            {"event_type": "note", "udfører": "support2", "text": "Kontoen er låst efter for mange fejlede forsøg. Oplåst og ny adgangskode sat."},
            {"event_type": "comment", "udfører": "karlslunde", "text": "Hun kan logge ind nu. Tak!"},
            {"event_type": "resolve", "udfører": "support2"},
        ],
    },
]
